# Generated by Django 5.2.7 on 2026-05-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_picker_perf_sheet_default_oct30'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentWorkbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional label in Admin only.', max_length=200, verbose_name='Title (optional)')),
                ('file', models.FileField(help_text='Upload Environment-Tamer-Logistics.xlsx. Expected sheets include Data Governance, 1. Electricty, 2. Energy, 3. Transportation, 4. Water - LITERS, 5. Waste, 6. Fugitive gases.', upload_to='environment_workbooks/%Y/%m/', verbose_name='Workbook (.xlsx / .xlsm)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only one active workbook is shown on the public dashboard.', verbose_name='Active')),
                ('parsed_snapshot', models.JSONField(blank=True, editable=False, help_text='Filled when the file is saved if the workbook structure is valid.', null=True, verbose_name='Parsed ESG data (auto)')),
            ],
            options={
                'verbose_name': 'Environment ESG workbook',
                'verbose_name_plural': 'Environment ESG workbooks',
                'ordering': ('-uploaded_at',),
            },
        ),
    ]
