# Generated by Django 5.2.7 on 2026-05-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_environmentworkbook_report_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentworkbook',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active workbook for this report year on the public dashboard.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='environmentworkbook',
            name='report_year',
            field=models.PositiveIntegerField(default=2025, help_text='Reporting year (e.g. 2025 or 2026). Only one active workbook per year.', verbose_name='Report year'),
        ),
    ]
