# Generated by Django 5.2.7 on 2026-05-20 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_reportyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barrierchallenge',
            name='program',
        ),
        migrations.DeleteModel(
            name='DashboardWorkbook',
        ),
        migrations.RemoveField(
            model_name='pickershiftrecord',
            name='program',
        ),
        migrations.RemoveField(
            model_name='pickingmethodphase',
            name='program',
        ),
        migrations.RemoveField(
            model_name='pickingmethodphasetag',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='pickingmethodsummarycard',
            name='program',
        ),
        migrations.RemoveField(
            model_name='processimprovementitem',
            name='program',
        ),
        migrations.RemoveField(
            model_name='productivitydashboardcard',
            name='dashboard',
        ),
        migrations.RemoveField(
            model_name='rolloutplancard',
            name='program',
        ),
        migrations.DeleteModel(
            name='BarrierChallenge',
        ),
        migrations.DeleteModel(
            name='BarrierProgram',
        ),
        migrations.DeleteModel(
            name='PickerPerformanceProgram',
        ),
        migrations.DeleteModel(
            name='PickerShiftRecord',
        ),
        migrations.DeleteModel(
            name='PickingMethodPhase',
        ),
        migrations.DeleteModel(
            name='PickingMethodPhaseTag',
        ),
        migrations.DeleteModel(
            name='PickingMethodProgram',
        ),
        migrations.DeleteModel(
            name='PickingMethodSummaryCard',
        ),
        migrations.DeleteModel(
            name='ProcessImprovementItem',
        ),
        migrations.DeleteModel(
            name='ProcessImprovementProgram',
        ),
        migrations.DeleteModel(
            name='ProductivityDashboard',
        ),
        migrations.DeleteModel(
            name='ProductivityDashboardCard',
        ),
        migrations.DeleteModel(
            name='RolloutPlanCard',
        ),
        migrations.DeleteModel(
            name='RolloutProgram',
        ),
    ]
