# Generated by Django 5.2.7 on 2026-05-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_remove_warehouse_legacy_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentworkbook',
            name='file',
            field=models.FileField(help_text='Upload Environment-Tamer-Logistics-{report_year}.xlsx (e.g. Environment-Tamer-Logistics-2026.xlsx). Expected sheets: Data Governance, 1. Electricty, 2. Energy, 3. Transportation, 4. Water - LITERS, 5. Waste, 6. Fugitive gases.', upload_to='environment_workbooks/%Y/%m/', verbose_name='Workbook (.xlsx / .xlsm)'),
        ),
    ]
